;; Sane defaults
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq dired-use-ls-dired nil)
(setq ring-bell-function 'ignore)
(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)        ; Give some breathing room
(delete-selection-mode 1)   ; Act like a normal editor
(electric-pair-mode 1)
(menu-bar-mode 1)

;; Programming Modes
(add-hook 'prog-mode-hook 'display-line-numbers-mode)

;; Configure the Modus Themes' appearance
(setq modus-themes-mode-line '(accented borderless)
      modus-themes-bold-constructs t
      modus-themes-italic-constructs t
      modus-themes-fringes 'subtle
      modus-themes-tabs-accented t
      modus-themes-paren-match '(bold intense)
      modus-themes-prompts '(bold intense)
      modus-themes-completions 'opinionated
      modus-themes-org-blocks 'tinted-background
      modus-themes-scale-headings t
      modus-themes-region '(bg-only)
      modus-themes-headings
      '((1 . (rainbow overline background 1.4))
        (2 . (rainbow background 1.3))
        (3 . (rainbow bold 1.2))
        (t . (semilight 1.1))))

;; Load the dark theme by default
(load-theme 'modus-operandi t)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
 (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
   (package-install 'use-package))

(require 'use-package)

;; Compilation Mode Setup
(use-package compile
  :init
  (setq ansi-color-for-compilation-mode t)
  :ensure nil
  :config (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter))

;; Compilation Settings
(defconst typescript-tsc-error-regexp
  (concat
   "^[[:blank:]]*"
   "\\([^(\r\n)]+\\)(\\([0-9]+\\),\\([0-9]+\\)):[[:blank:]]+"
   "error [[:alnum:]]+: [^\r\n]+$")
  "Regexp to match errors generated by tsc.")

;; handle pretty compiler-errors like the following when doing M-x compile<ret>tsc<ret>
;; test.ts:2:7 - error TS2322: Type '2' is not assignable to type 'string'.
(defconst typescript-tsc-pretty-error-regexp
  (concat
   "^[[:blank:]]*"
   "\\([^(\r\n)]+\\):\\([0-9]+\\):\\([0-9]+\\) - [[:blank:]]*"
   "error [[:alnum:]]+: [^\r\n]+$")
  "Regexp to match errors generated by tsc.")

;; (dolist
;;     (regexp
;;      `((typescript-tsc
;;         ,typescript-tsc-error-regexp
;;         1 2 3 2)

;;        (typescript-tsc-pretty
;;         ,typescript-tsc-pretty-error-regexp
;;         1 2 3 2)))
;;   (add-to-list 'compilation-error-regexp-alist-alist regexp)
;;   (add-to-list 'compilation-error-regexp-alist (car regexp)))

;; Project management
(use-package project
  :init
  (setq project-switch-commands 'magit-status)
  :bind-keymap
  ("C-c p" . project-prefix-map)
  :bind (:map project-prefix-map
         ("h" . project-find-file)))

;; Buffer Completion
(use-package vertico
  :ensure t
  :init
  (vertico-mode))

(use-package orderless
  :ensure t
  :init
  (setq completion-styles '(orderless basic))
  (setq orderless-matching-styles '(orderless-literal orderless-regexp)))


;; Git Interface
(use-package magit
  :ensure t
  :init
  (setq magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)
  :bind (("C-c m" . magit-status)))

;; (use-package forge
;;   :after magit
;;   :config
;;   (add-to-list 'forge-alist '("code.corp.indeed.com" "code.corp.indeed.com/api/v4" "code.corp.indeed.com" forge-gitlab-repository)))

;; (use-package which-key
;;   :config
;;   (which-key-mode))

(use-package exec-path-from-shell
  :ensure t
  :config
  (exec-path-from-shell-initialize))

(use-package web-mode
  :ensure t
  :init
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  :mode (("\\.js\\'" . web-mode)
	 ("\\.jsx\\'" .  web-mode)
	 ("\\.ts\\'" . web-mode)
	 ("\\.tsx\\'" . web-mode)
	 ("\\.html\\'" . web-mode))
  :commands web-mode
)

(use-package lsp-mode
  :ensure t
  :init
  (setq read-process-output-max (* 1024 1024)) ;; 1mb
  (setq gc-cons-threshold 100000000)
  (setq lsp-keymap-prefix "C-c l")
  (setq lsp-headerline-breadcrumb-enable nil)
  :hook ((web-mode . lsp-deferred)))

;; (use-package lsp-ui
;;   :commands lsp-ui-mode)

(use-package prettier-js
  :ensure t
  :hook (web-mode . prettier-js-mode))

(use-package org
  :ensure t
  :init
  (setq org-directory "~/Sync/org")
  (setq org-agenda-files '("~/Sync/org"))
  (setq org-default-notes-file (concat org-directory "/today.org"))
  :bind
  (("C-c t" . find-default-notes-file)
   ("C-c a" . org-agenda)))

(use-package org-capture
  :init
  (setq org-capture-templates
                 '(("t" "Task" entry
                   (file+headline org-default-notes-file "Tasks")
                   "* TODO %?" :prepend t)
		   ("s" "Standup Status" entry
                    (file+datetree "status.org" "Statuses")
		    (file "templates/status")
		    :prepend t)))
  :bind
  ("C-c c" . org-capture))

(defun find-default-notes-file ()
  (interactive)
  (find-file org-default-notes-file))

(use-package multiple-cursors
  :ensure  t
  :bind (("H-SPC" . set-rectangular-region-anchor)
         ("C-M-SPC" . set-rectangular-region-anchor)
         ("C->" . mc/mark-next-like-this)
         ("C-<" . mc/mark-previous-like-this)
         ("C-c C->" . mc/mark-all-like-this)
         ("C-c C-SPC" . mc/edit-lines)
         ))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(web-mode-comment-formats
   '(("java" . "/*")
     ("javascript" . "//")
     ("typescript" . "//")
     ("php" . "/*")
     ("css" . "/*"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
