(setq inhibit-startup-message t)

(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)        ; Give some breathing room
(delete-selection-mode 1)   ; Act like a normal editor
(electric-pair-mode 1)


(defconst typescript-tsc-error-regexp
  (concat
   "^[[:blank:]]*"
   "\\([^(\r\n)]+\\)(\\([0-9]+\\),\\([0-9]+\\)):[[:blank:]]+"
   "error [[:alnum:]]+: [^\r\n]+$")
  "Regexp to match errors generated by tsc.")

;; handle pretty compiler-errors like the following when doing M-x compile<ret>tsc<ret>
;; test.ts:2:7 - error TS2322: Type '2' is not assignable to type 'string'.
(defconst typescript-tsc-pretty-error-regexp
  (concat
   "^[[:blank:]]*"
   "\\([^(\r\n)]+\\):\\([0-9]+\\):\\([0-9]+\\) - [[:blank:]]*"
   "error [[:alnum:]]+: [^\r\n]+$")
  "Regexp to match errors generated by tsc.")


(menu-bar-mode 1)
(setq dired-use-ls-dired nil)
;; Set up the visible bell
;;(setq visible-bell t)

;;(set-face-attribute 'default nil :font "Fira Code Retina" :height 280)

(load-theme 'tango)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
 (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
   (package-install 'use-package))

(require 'use-package)

;; Compilation Mode Setup
(use-package compile
  :ensure nil
  :config (add-hook 'compilation-filter-hook 'ansi-color-compilation-filter))

;; (dolist
;;     (regexp
;;      `((typescript-tsc
;;         ,typescript-tsc-error-regexp
;;         1 2 3 2)

;;        (typescript-tsc-pretty
;;         ,typescript-tsc-pretty-error-regexp
;;         1 2 3 2)))
;;   (add-to-list 'compilation-error-regexp-alist-alist regexp)
;;   (add-to-list 'compilation-error-regexp-alist (car regexp)))

;; Initialize package sources
(use-package project
  :init
  (setq project-switch-commands 'magit-status)
  :bind-keymap
  ("C-c p" . project-prefix-map)
  :bind (:map project-prefix-map
         ("h" . project-find-file)))


;; ;; Buffer Completion
;; (use-package ivy
;;   :config
;;   (ivy-mode 1))
;; (use-package prescient)
;; (use-package ivy-prescient
;;   :config
;;   (ivy-prescient-mode t))

;; Buffer Completion
;; (use-package selectrum
;;   :init
;;   (selectrum-mode +1))

;; Buffer Completion
(use-package vertico
  :ensure t
  :init
  (vertico-mode))

(use-package orderless
  :ensure t
  :init
  ;; Configure a custom style dispatcher (see the Consult wiki)
  ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
  ;;       orderless-component-separator #'orderless-escapable-split-on-space;; )
  (setq completion-styles '(orderless basic))
  (setq orderless-matching-styles '(orderless-literal orderless-regexp)))

;; Project Management
(require 'project)

;; Git Interface
(use-package magit
  :ensure t
  :init
  (setq magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)
  :bind (("C-c m" . magit-status)))

;; (use-package forge
;;   :after magit
;;   :config
;;   (add-to-list 'forge-alist '("code.corp.indeed.com" "code.corp.indeed.com/api/v4" "code.corp.indeed.com" forge-gitlab-repository)))

;; (use-package which-key
;;   :config
;;   (which-key-mode))

(use-package exec-path-from-shell
  :ensure t
  :config
  (exec-path-from-shell-initialize))

(use-package web-mode
  :ensure t
  :init
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  :mode (("\\.js\\'" . web-mode)
	 ("\\.jsx\\'" .  web-mode)
	 ("\\.ts\\'" . web-mode)
	 ("\\.tsx\\'" . web-mode)
	 ("\\.html\\'" . web-mode))
  :commands web-mode
)

(use-package lsp-mode
  :ensure t
  :init
  (setq read-process-output-max (* 1024 1024)) ;; 1mb
  (setq gc-cons-threshold 100000000)
  (setq lsp-keymap-prefix "C-c l")
  (setq lsp-headerline-breadcrumb-enable nil)
  :hook ((web-mode . lsp-deferred)))

;; (use-package lsp-ui
;;   :commands lsp-ui-mode)

(use-package prettier-js
  :ensure t
  :hook (web-mode . prettier-js-mode))

(use-package org
  :ensure t
  :init
  (setq org-directory "~/Sync/org")
  (setq org-agenda-files '("~/Sync/org"))
  (setq org-default-notes-file (concat org-directory "/today.org"))
  :bind
  (("C-c t" . find-default-notes-file)
   ("C-c a" . org-agenda)))

(use-package org-capture
  :init
  (setq org-capture-templates
                 '(("t" "Task" entry
                   (file+headline org-default-notes-file "Tasks")
                   "* TODO %?" :prepend t)
		   ("s" "Standup Status" entry
                    (file+datetree "status.org" "Statuses")
		    (file "templates/status")
		    :prepend t)))
  :bind
  ("C-c c" . org-capture))

(defun find-default-notes-file ()
  (interactive)
  (find-file org-default-notes-file))

(use-package multiple-cursors
  :ensure  t
  :bind (("H-SPC" . set-rectangular-region-anchor)
         ("C-M-SPC" . set-rectangular-region-anchor)
         ("C->" . mc/mark-next-like-this)
         ("C-<" . mc/mark-previous-like-this)
         ("C-c C->" . mc/mark-all-like-this)
         ("C-c C-SPC" . mc/edit-lines)
         ))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-for-compilation-mode t)
 '(completion-styles '(flex basic partial-completion emacs22))
 '(custom-safe-themes
   '("37768a79b479684b0756dec7c0fc7652082910c37d8863c35b702db3f16000f8" "1436985fac77baf06193993d88fa7d6b358ad7d600c1e52d12e64a2f07f07176" default))
 '(make-backup-files nil)
 '(package-selected-packages
   '(vertico multiple-cursors forge org-mode ivy-prescient nord-theme dracula-theme orderless selectrum lsp-mode prettier-js which-key web-mode use-package project magit lsp-ui ivy exec-path-from-shell command-log-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
